### ISSUE TITLE
Is this going to be pushed eventually?

### ISSUE THREAD

**Issue by busti** [pitkley/jmccs-win#1]
Title

**Comment by pitkley** [comment]
If by "pushed" you mean pushed to Maven central, then the answer is probably no. The snapshot versions are available through the [Sonatype OSS snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/) though.

To add the snapshot repository to your Maven build, something like the following should work:

```xml
<project>
...
   <repositories>
     <repository>
       <id>snapshots-repo</id>
       <url>https://oss.sonatype.org/content/repositories/snapshots</url>
       <releases><enabled>false</enabled></releases>
       <snapshots><enabled>true</enabled></snapshots>
     </repository>
   </repositories>
...
</project>
```

Then you can depend on `0.2.1-SNAPSHOT`:

```xml
<dependencies>
...
  <dependency>
    <groupId>de.pitkley</groupId>
    <artifactId>jmccs-win</artifactId>
    <version>0.2.1-SNAPSHOT</version>
  </dependency>
...
</dependencies>
```

I hope this helps.

**Comment by busti** [comment]
Thanks, that is exactly what I needed.  
I could have linked the repo into my project but that would have gotten messy really quickly. This however is perfect, keeps the build-script nice and clean

**Comment by pitkley** [comment]
Cool, thanks for letting me know that this works for you. :+1: Hope you find use in jMCCS!
